language: python
python: "2.7"
branches:
    only:
        - master
install:
    - "pip install -r requirements.txt"
    - "pip install pep8"
script:
    - "pep8 plugin"
    - "nosetests plugin/tests.py -v"
